### ISSUE TITLE
Docs cannot be navigated in GitHub

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#126] opened 2019-07-02 09:04 UTC
The current docs hierarchy works fine in gitbook with the lateral navigation menu, but when visiting in GitHub there are sections that are not accessible from the main README.

For example: command reference, multiple datasets, etc.

**Comment by dpordomingo** [comment] 2019-07-02 09:29
well... we decide to make GitBook our entry point, and there is a link to the proper docs.
But would be enough to satisfy your request if adding this other link?

![image](https://user-images.githubusercontent.com/2437584/60501610-96d77c80-9cbc-11e9-8567-d54e56f94d97.png)

The problem is that adding that contents into the README will duplicate them in GitBook, that I think would be worst considering our goals.

**Comment by carlosms** [comment] 2019-07-02 10:13
I'd prefer to make everything work on GitHub (or in a local clone).

- https://github.com/src-d/sourced-ce/blob/master/docs/quickstart/README.md is linked from https://github.com/src-d/sourced-ce#quick-start
- https://github.com/src-d/sourced-ce/blob/master/docs/architecture.md is linked from https://github.com/src-d/sourced-ce#architecture
- https://github.com/src-d/sourced-ce/blob/master/docs/CONTRIBUTING.md is linked from https://github.com/src-d/sourced-ce#contributing

The only thing missing is getting to the docs in https://github.com/src-d/sourced-ce/blob/master/docs/usage. I think we could just copy or move the contents of https://github.com/src-d/sourced-ce/blob/master/docs/usage/README.md to a new section in the main README right below the quick start.

**Comment by dpordomingo** [comment] 2019-07-02 19:19
Since we decided to use GitBook as our standard and the promoted way to render our docs, I'd not extract every content from `docs` into the main `README.md` because it would make the docs too verbose and repetitive (we could also see it as disturbing in [one of our empathy sessions](https://github.com/src-d/empathy-sessions/issues/40), that even finds confusing our current docs with fewer dupes than the proposed alternative).

Also, we currently put our docs [in `docs` folder](https://github.com/src-d/sourced-ce/tree/master/docs), which is a kind of convention in OS repos, so it would be easily found by any potential visitor of our repo in GitHub.

Anyhow, I'm not against promoting our current [`docs/README`](https://github.com/src-d/sourced-ce/tree/master/docs) in our main `README.md`, but I'd like to find a better way than linking there every single thing that can be found in `docs` (which would not be maintainable in the long term).

**PROPOSAL:**
Would you find useful if instead of the phrase I added in the screenshot above, we add a link to `docs/usage/README.md` in our current `README.md#quickstart`?
That way, these other resources will be clearly promoted in our quickstart from our main `README.md` (for the small group of users visiting our docs from GitHub).
-> implemented by https://github.com/src-d/sourced-ce/pull/127
-> example at https://dpordomingo.gitbook.io/community-edition/#quick-start

**Comment by se7entyse7en** [comment] 2019-10-18 11:16
Closed by #127.

**Closed as completed by se7entyse7en** 2019-10-18 11:16 UTC
Labels: enhancement
