### ISSUE TITLE
gitbase not container not stopped, sourced-ce fails to start

### ISSUE THREAD

**Issue by marnovo** [src-d/sourced-ce#57] opened 2019-06-18 12:01 UTC
Sometimes gitbase container doesn't stop with `sourced stop`, then `sourced start` fails due to port conflict.
Then you have to stop the container manually using Docker, and `sourced start` works as expected.

Not sure how I quit it last time, maybe this is related? However surely Docker was quit in between.

Versions:

- OS: macOS Mojave 10.14.5 (18F132)
- Docker: 2.0.0.3
- `sourced` binary: [v0.14.0-beta.1](https://github.com/src-d/sourced-ce/tree/v0.14.0-beta.1)

Log:
```bash
$ ./sourced start
Starting bblfsh     ... done
Starting gitbase    ... error
Starting bblfsh-web ... done
Starting redis      ... done
Starting postgres   ... done
Starting sourced-ui ... error

ERROR: for gitbase  Cannot start service gitbase: driver failed programming external connectivity on endpoint srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_gitbase_1 (ba83c96b32371a45024f4ccdc9a9079304db1aa202c0b1f6928c9fda2972ddcb): Bind for 0.0.0.0:3306 failed: port is already allocated
Initializing source{d}... ⠸^C

$ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                      PORTS                    NAMES
7de285894081        srcd/sourced-ui:v0.1.0           "/entrypoint.sh"         13 days ago         Exited (137) 11 days ago                             srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_sourced-ui_1
a5bcb5bcf5d5        bblfsh/web:v0.11.0               "/bin/bblfsh-web -ad…"   13 days ago         Up 21 seconds               0.0.0.0:9999->8080/tcp   srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh-web_1
e068969470a7        srcd/gitbase:v0.20.0             "./init.sh"              13 days ago         Exited (255) 11 days ago                             srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_gitbase_1
b76975d14aff        redis:3.2                        "docker-entrypoint.s…"   13 days ago         Up 21 seconds               0.0.0.0:6379->6379/tcp   srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_redis_1
3ec8761c7afa        postgres:10                      "docker-entrypoint.s…"   13 days ago         Up 22 seconds               0.0.0.0:5432->5432/tcp   srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_postgres_1
6ed58b31d5f6        bblfsh/bblfshd:v2.14.0-drivers   "/tini -- bblfshd"       13 days ago         Up 22 seconds               0.0.0.0:9432->9432/tcp   srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh_1
cf96a5f9dee5        srcd/sourced-ui:v0.1.0           "/entrypoint.sh"         13 days ago         Exited (137) 13 days ago                             srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_sourced-ui_1
c89b7ef19b92        srcd/gitbase:v0.20.0             "./init.sh"              13 days ago         Up 22 hours                 0.0.0.0:3306->3306/tcp   srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_gitbase_1
dea48225e14a        bblfsh/web:v0.11.0               "/bin/bblfsh-web -ad…"   13 days ago         Exited (2) 13 days ago                               srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_bblfsh-web_1
c82fd2a398d3        redis:3.2                        "docker-entrypoint.s…"   13 days ago         Exited (0) 13 days ago                               srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_redis_1
70d5a2a4edb0        postgres:10                      "docker-entrypoint.s…"   13 days ago         Exited (0) 13 days ago                               srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_postgres_1
0a4d034d71a6        bblfsh/bblfshd:v2.14.0-drivers   "/tini -- bblfshd"       13 days ago         Exited (255) 22 hours ago   0.0.0.0:9432->9432/tcp   srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_bblfsh_1

$ ./sourced stop
Stopping srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh-web_1 ... done
Stopping srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_redis_1      ... done
Stopping srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_postgres_1   ... done
Stopping srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh_1     ... done

$ ./sourced stop

sourced-ce/build on  master > docker container list -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                      PORTS                    NAMES
7de285894081        srcd/sourced-ui:v0.1.0           "/entrypoint.sh"         13 days ago         Exited (137) 11 days ago                             srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_sourced-ui_1
a5bcb5bcf5d5        bblfsh/web:v0.11.0               "/bin/bblfsh-web -ad…"   13 days ago         Exited (2) 29 seconds ago                            srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh-web_1
e068969470a7        srcd/gitbase:v0.20.0             "./init.sh"              13 days ago         Exited (255) 11 days ago                             srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_gitbase_1
b76975d14aff        redis:3.2                        "docker-entrypoint.s…"   13 days ago         Exited (0) 29 seconds ago                            srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_redis_1
3ec8761c7afa        postgres:10                      "docker-entrypoint.s…"   13 days ago         Exited (0) 29 seconds ago                            srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_postgres_1
6ed58b31d5f6        bblfsh/bblfshd:v2.14.0-drivers   "/tini -- bblfshd"       13 days ago         Exited (1) 29 seconds ago                            srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh_1
cf96a5f9dee5        srcd/sourced-ui:v0.1.0           "/entrypoint.sh"         13 days ago         Exited (137) 13 days ago                             srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_sourced-ui_1
c89b7ef19b92        srcd/gitbase:v0.20.0             "./init.sh"              13 days ago         Up 22 hours                 0.0.0.0:3306->3306/tcp   srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_gitbase_1
dea48225e14a        bblfsh/web:v0.11.0               "/bin/bblfsh-web -ad…"   13 days ago         Exited (2) 13 days ago                               srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_bblfsh-web_1
c82fd2a398d3        redis:3.2                        "docker-entrypoint.s…"   13 days ago         Exited (0) 13 days ago                               srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_redis_1
70d5a2a4edb0        postgres:10                      "docker-entrypoint.s…"   13 days ago         Exited (0) 13 days ago                               srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_postgres_1
0a4d034d71a6        bblfsh/bblfshd:v2.14.0-drivers   "/tini -- bblfshd"       13 days ago         Exited (255) 22 hours ago   0.0.0.0:9432->9432/tcp   srcd-d88690e30386069096c7c33915c6dbbbc084c9e7_bblfsh_1

$ docker container stop c89b7ef19b92
c89b7ef19b92

$ ./sourced status
                           Name                                         Command                State     Ports
--------------------------------------------------------------------------------------------------------------
srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh-web_1   /bin/bblfsh-web -addr :808 ...   Exit 2
srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_bblfsh_1       /tini -- bblfshd                 Exit 1
srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_gitbase_1      ./init.sh                        Exit 255
srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_postgres_1     docker-entrypoint.sh postgres    Exit 0
srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_redis_1        docker-entrypoint.sh redis ...   Exit 0
srcd-807c4ceaea185dbe21b14b6f7955d1722ddca312_sourced-ui_1   /entrypoint.sh                   Exit 137

$ ./sourced start
Starting bblfsh     ... done
Starting gitbase    ... done
Starting bblfsh-web ... done
Starting redis      ... done
Starting postgres   ... done
Starting sourced-ui ... done
```

**Comment by smola** [comment] 2019-06-18 12:50
@marnovo Which operating system?

**Comment by marnovo** [comment] 2019-06-18 15:23
Sorry, forgot to provide the details. Along the way noticed I was running a version that's now a bit "dated"—so will try again with the new beta versions. Edited the parent post with the details.

**Comment by marnovo** [comment] 2019-06-20 08:25
Update:

Last evening I was updating from [v0.14.0-beta.4](https://github.com/src-d/sourced-ce/releases/tag/v0.14.0-beta.4) to [v0.14.0-beta.5](https://github.com/src-d/sourced-ce/releases/tag/v0.14.0-beta.5), and when I ran the prune before updating, I noticed that gitbase and bblfsh countainers were stopped (thus I guess were still running before it), so I guess this is still happening?

Log:
```bash
$ ./sourced prune --all
Stopping srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_gitbase_1 ... done
Stopping srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_bblfsh_1  ... done
Removing srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_sourced-ui_1 ... done
Removing srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_bblfsh-web_1 ... done
Removing srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_gitbase_1    ... done
Removing srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_postgres_1   ... done
Removing srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_redis_1      ... done
Removing srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_bblfsh_1     ... done
Removing network srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_default
Removing volume srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_gitbase_indexes
Removing volume srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_postgres
Removing volume srcd-7197889e4694ee9a6ae882a9550fe0d7f81e38aa_redis
```

**Comment by dpordomingo** [comment] 2019-06-25 19:57
Let me explain what I think that it could happen:
- you changed your workdir without properly stopping components from old workdir.

**How do I know it?**
Because the running `gitbase` belongs to a different workspace than the other running components (as you can see on components prefix names)

**How could it happen?**
Not sure, but let me help to reproduce it.
If, for example, you delete `~/.sourced` directory before running `prune`, you can ruin your installation if then you `init` with a different workdir (e.g. during an upgrade, when we recommend deleting `~/.sourced`).

**How to solve it?**
Run `init` again with the same old workdir, and then `prune`, and then `init` again. 

**And now, what?**
I see we have some problems:
1. this should not happen to the user: no matter if they delete `~/.sourced` before `stop`; `sourced` should be able to stop **ALL** components when running `stop`, no matter what is the active workdir,
1. we should ensure that `stop` actually stops all the workdirs (especially the current one), and there are no situations when it fails (no matter if the user press `CTRL+C` during the stopping process or whatever)
1. (and a deeper one) I never liked the way we handle workdirs and active dirs... and configs... because they can be ruined during the upgrade process or running commands in the wrong order. I'd suggest a more trustful way to handle those. I'd say that we need a more trustful way to store the sandbox state.

**Comment by se7entyse7en** [comment] 2019-10-18 14:47
This issue is very old, let's see how this relates to latest version, and eventually close this if doesn't apply anymore. @dpordomingo regarding the improvement for handling workdirs I'd suggest to open a separate issue.

**Comment by dpordomingo** [comment] 2019-10-21 09:53
related issue at https://github.com/src-d/sourced-ce/issues/259

**Comment by rpau** [comment] 2019-10-23 08:48
This is not reproducible.

**Closed as completed** 2019-10-23 08:48 UTC
Labels: bug
